<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.*" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.*" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.*" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="9.0.7" />
    <PackageReference Include="DotNet.Glob" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DatabaseLib\DatabaseLib\src\DatabaseLib\DatabaseLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <!-- 1. Define a variable that switches based on whether you are Building or Publishing -->
	  <PropertyGroup>
		  <CurrentOutputFolder>$(TargetDir)</CurrentOutputFolder>
		  <CurrentOutputFolder Condition="'$(PublishDir)' != ''">$(PublishDir)</CurrentOutputFolder>
	  </PropertyGroup>

	  <!-- 2. Pass that variable into your script or command -->
	  <Message Text="--- Post Build Event Output Path: $(CurrentOutputFolder) ---" Importance="high" />

	  <Exec Command="echo robocopy /MIR &quot;$(ProjectDir)sql&quot; &quot;$(CurrentOutputFolder)\sql&quot;&#xD;&#xA;robocopy /MIR &quot;$(ProjectDir)sql&quot; &quot;$(CurrentOutputFolder)\sql&quot; &gt;nul 2&gt;&amp;1&#xD;&#xA;robocopy /MIR &quot;$(ProjectDir)data&quot; &quot;$(CurrentOutputFolder)\data&quot; &gt;nul 2&gt;&amp;1&#xD;&#xA;    exit 0" />
  </Target>

</Project>
