name: CI
on:
  push:
    branches: [ main, develop, release/*, hotfix/* ]
  pull_request:
    branches: [ main, develop, release/*, hotfix/* ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout csharp_DotNet8_ODBC
        uses: actions/checkout@v4
        id: checkout_code_1
        with:
          repository: msi-cxb/csharp_DotNet8_ODBC
          path: './csharp_DotNet8_ODBC'
            
      - name: Checkout DatabaseLib
        uses: actions/checkout@v4
        id: checkout_code_2
        with:
          repository: msi-cxb/DatabaseLib
          path: './DatabaseLib'
            
      - name: install SQLite ODBC
        id: install_sqlite_odbc
        shell: cmd
        run: |
          cd .\csharp_DotNet8_ODBC\sqliteODBC64
          .\SQLiteODBCInstaller.exe -q -i -d=sql3

      - name: install DuckDB ODBC
        id: install_duckdb_odbc
        shell: cmd
        run: |
          cd .\csharp_DotNet8_ODBC\duckdbODBC64
          .\odbc_install.exe /CI /Install

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
              
      - name: Run MSBuild
        id: run_msbuild
        shell: cmd
        run: |
          cd .\csharp_DotNet8_ODBC
          rmdir /s /q .\bin
          rmdir /s /q .\obj
          msbuild .\csharp_DotNet8_ODBC.sln /p:Configuration=Release /p:PublishProfile="FolderProfile" /t:clean,restore,publish /p:PublishDir=".\bin\publish"
          dir /s /b .\*.exe

      - name: Run with sqlite3
        id: run_sqlite_executable
        shell: powershell
        run: |
          cd .\csharp_DotNet8_ODBC
          .\bin\publish\csharp_DotNet8_ODBC.exe --sql .\sql\sqlite3\*version*.sql
          if ($LASTEXITCODE) { exit $LASTEXITCODE }

      - name: Run with duckdb
        id: run_duckdb_executable
        shell: powershell
        run: |
          cd .\csharp_DotNet8_ODBC
          .\bin\publish\csharp_DotNet8_ODBC.exe --sql .\sql\duckdb\*version*.sql
          if ($LASTEXITCODE) { exit $LASTEXITCODE }
      
      - name: cache
        uses: actions/cache/save@v4
        with:
          path: .\csharp_DotNet8_ODBC\bin\publish
          key: cache-${{ github.run_id }}-${{ github.run_attempt }}
          enableCrossOsArchive: true

      - name: release
        id: release
        uses: ncipollo/release-action@v1
        with:
          replacesArtifacts: true
          artifacts: "csharp_DotNet8_ODBC.zip"
